#!/bin/bash

# launch a tmux session for a server, but not if the server is already running
# requires the additional start script specified at $startscr

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
lockfile="./server.running.lock"
startscr="./mc-server-start"

successprint() {
	echo "SERVER STARTED IN A DETACHED TMUX SESSION."
	echo " Use tmux commands to attach the session:"
	echo "   from outside tmux: tmux attach -t mcserver"
	echo "    from inside tmux: C-b s"
}

if [ -e "$lockfile" ]; then
	echo "Launch Abort. Server is already running."
	exit 1
else
	if [ -e "$startscr" ]; then
		tmux new -d -s mcserver "$startscr" && successprint
		# tmux provides an additional check; it wont create 
		# a session by name if it already exists.
		exit 0
	else
		echo "Launch Abort. Launch script missing."
		exit 1
	fi
fi
